CREATE TABLE IF NOT EXISTS tiktok_sync_snapshots (
  client_id INTEGER PRIMARY KEY,
  spend NUMERIC(14,2) NOT NULL DEFAULT 0,
  impressions INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  conversions INTEGER NOT NULL DEFAULT 0,
  revenue NUMERIC(14,2) NOT NULL DEFAULT 0,
  synced_at TIMESTAMP NOT NULL DEFAULT NOW()
);
